build:
	# No build step needed for TypeScript files, but you can add a type check if desired
	# tsc --noEmit nbody.ts
	# Uncomment the line above to perform a type check without emitting JavaScript files
	# Maybe get node modules
run:
	deno nbody.ts 50000000